finished incomplete error message

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2376,8 +2376,8 @@ yes)
   # target-specific build rules, so it will be forcibly enabled
   # (unless the Java language itself isn't enabled).
   if test "x${ENABLE_ULIBGCJ}" = "xyes" ; then
-    { { echo "$as_me:$LINENO: error: micro-libgcj" >&5
-echo "$as_me: error: micro-libgcj" >&2;}
+    { { echo "$as_me:$LINENO: error: micro-libgcj and libgcj are mutually exclusive" >&5
+echo "$as_me: error: micro-libgcj and libgcj are mutually exclusive" >&2;}
    { (exit 1); exit 1; }; }
   fi
   libgcj=
