various build fixes

diff --git a/ulibgcj/configure b/ulibgcj/configure
--- a/ulibgcj/configure
+++ b/ulibgcj/configure
@@ -748,7 +748,7 @@ USING_NO_THREADS_TRUE
 USING_NO_THREADS_FALSE
 HASH_SYNC_SPEC
 GCJH
-ZIP
+JAR
 CPP
 GREP
 EGREP
@@ -4829,12 +4829,58 @@ fi
 built_gcc_dir="`cd ../../${host_subdir}/gcc && ${PWDCMD-pwd}`"
 GCJ="${built_gcc_dir}/gcj -B${built_gcc_dir}/"
 GCJH="${built_gcc_dir}/gcjh"
-built_fastjar_dir="`cd ../../${host_subdir}/fastjar && ${PWDCMD-pwd}`"
-ZIP="${built_fastjar_dir}/fastjar"
 
 
 
 
+for ac_prog in jar fastjar
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_JAR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$JAR"; then
+  ac_cv_prog_JAR="$JAR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_JAR="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+JAR=$ac_cv_prog_JAR
+if test -n "$JAR"; then
+  { echo "$as_me:$LINENO: result: $JAR" >&5
+echo "${ECHO_T}$JAR" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$JAR" && break
+done
+test -n "$JAR" || JAR="no"
+
+if test "$JAR" = no; then
+  { { echo "$as_me:$LINENO: error: cannot find jar command, cannot continue" >&5
+echo "$as_me: error: cannot find jar command, cannot continue" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 if test -d sysdep; then true; else mkdir sysdep; fi
 ac_config_links="$ac_config_links sysdep/locks.h:${libjava}/sysdep/$sysdeps_dir/locks.h"
@@ -6555,7 +6601,7 @@ USING_NO_THREADS_TRUE!$USING_NO_THREADS_TRUE$ac_delim
 USING_NO_THREADS_FALSE!$USING_NO_THREADS_FALSE$ac_delim
 HASH_SYNC_SPEC!$HASH_SYNC_SPEC$ac_delim
 GCJH!$GCJH$ac_delim
-ZIP!$ZIP$ac_delim
+JAR!$JAR$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
